## file: hosts_tests.yml
# hosts
localhost ansible_host=127.0.0.1 ansible_connection=local

[tests]
test    ansible_host=192.168.99.30
test01  ansible_host=192.168.99.31
test02  ansible_host=192.168.99.32
test03  ansible_host=192.168.99.33

[tests:vars]
ansible_connection=ssh
ansible_user=vagrant
ansible_ssh_private_key_file="~/.ssh/vagrant.pem"
